// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD69bsX3zNmAczNTPSYr4WKNrdS0ZdgE4w',
    appId: '1:1092344697980:web:4b238df9d90a334ce425f9',
    messagingSenderId: '1092344697980',
    projectId: 'chat-app-f1287',
    authDomain: 'chat-app-f1287.firebaseapp.com',
    storageBucket: 'chat-app-f1287.appspot.com',
    measurementId: 'G-8MBM8WT6XP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVS3Hing5g4KtBOF5lPU5cW4MztPSEE9I',
    appId: '1:1092344697980:android:a454b068a8b47828e425f9',
    messagingSenderId: '1092344697980',
    projectId: 'chat-app-f1287',
    storageBucket: 'chat-app-f1287.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH6PJymPu1_bajd2pzM9YpeK7Bs9yYQus',
    appId: '1:1092344697980:ios:809c53db22bcff2ce425f9',
    messagingSenderId: '1092344697980',
    projectId: 'chat-app-f1287',
    storageBucket: 'chat-app-f1287.appspot.com',
    iosClientId: '1092344697980-pgbavn9hfq746rk0pr5jm9ebv1em8bkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH6PJymPu1_bajd2pzM9YpeK7Bs9yYQus',
    appId: '1:1092344697980:ios:809c53db22bcff2ce425f9',
    messagingSenderId: '1092344697980',
    projectId: 'chat-app-f1287',
    storageBucket: 'chat-app-f1287.appspot.com',
    iosClientId: '1092344697980-pgbavn9hfq746rk0pr5jm9ebv1em8bkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp1',
  );
}
